# input: eth0
id: feature_extension_1
name: feature extension 1
description: example feature extraction description
authors: flan ben flan
license: BSD
version: 1.0

runtime: 
  name: extension.py

# dependencies: dependecies # TODO
requirements: requirements.txt # .yaml

# plugins:
#   - plugin1
#   - plugin2

log:
  dir: /logs
  # Setting the log level: CRITICAL, ERROR, WARNING, INFO, DEBUG
  level: INFO 

# data:
#   model: path/to/model.pickle # csv, ...
#   key: path/to/key.pem # specify the key when the model is crypted
#   batch_size: 200
#   format: pytorch # tensorflow, ONNX...
#   device: CPU # , GPU



repository: https://github.com/path/to/repository.git

# TODO: Comment each use case
channels:
  input: []
  subscribe: []
  publish: []

# Additional options for custom uses
# Examples: calls for external data or service
# options:
#   virustotal:
#     url: http://example.com/
#     api_key: api_key


# Additional options for custom uses
# Examples: logging to server
# options:
#   logstash:
#     # url: http://example.com/
#     port: port
#     index: index_name
#     keywords: []
#   elastic:
#     # url: http://example.com
#     index: index_name
    